import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Lenify from "@/components/lenify";
import Script from "next/script";
import { HighlightInit } from "@highlight-run/next/highlight-init";

export const metadata = {
  title: "Yorck - Crypto Monitoring",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <HighlightInit
        projectId={"jd41k4d5"}
        tracingOrigins
        networkRecording={{
          enabled: true,
          recordHeadersAndBody: true,
          urlBlocklist: [],
        }}
      />
      <ClerkProvider>
        <html lang="en" suppressHydrationWarning>
          <head>
            <Script
              defer
              src="https://analytics.umami.is/script.js"
              data-website-id="2df16cd7-bf77-4614-9d85-a7f37edeee52"
            />
          </head>
          <body>
            <Lenify />
            <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
              {children}
            </ThemeProvider>
            <Toaster />
          </body>
        </html>
      </ClerkProvider>
    </>
  );
}
